### ISSUE TITLE
No output (or warnings) from program run

### ISSUE THREAD

**Issue by pd-gmit** [partageit/markdown-to-slides#1]
Hi,
I installed markdown-to-slides and then tried to use/run the but I have no output from the program at all.
This was the command line:

```
$ markdown-to-slides paul-slides.md -o slideshow.html       [NO OUTPUT FROM PROGRAM]

$ file /usr/local/bin/markdown-to-slides
/usr/local/bin/markdown-to-slides: symbolic link to `../lib/node_modules/markdown-to-slides/index.js'
```

Am I doing something wrong?  Thanks.

**Comment by partageit** [comment]
Hello,
It seems to be normal, as long as `slideshow.html` is correctly generated.
Is it generated?
David

**Comment by pd-gmit** [comment]
No -  there was no output file "slideshow.html" generated. There was no output file of any type created.

**Comment by partageit** [comment]
Can you give me more details ? :)
- The NodeJS version with `node -v`
- The markdown-to-slides version with `markdown-to-slides -v`

What happens when you type:

```
markdown-to-slides paul-slides.md
```

without any other parameters?

**Comment by pd-gmit** [comment]
Its Working! 

I re-installed  Nodejs  ( using details on this webpage [https://github.com/joyent/node/wiki/installing-node.js-via-package-manager#debian-and-ubuntu-based-linux-distributions] )

For ref: this is the *node-js"  and "markdown-to-slides" versions I now have.

```
$ nodejs -v
v0.10.36

$ markdown-to-slides -v 
markdown-to-slides v1.0.1
```

Thanks for the software by the way it will be a great help.

**Comment by partageit** [comment]
Great, you are welcome :)

If you are interested in Markdown to slideshow converters, I work on another project: Vegetables.
It is a kind of markdown-to-slides, with a serve feature.

https://www.npmjs.com/package/vegetables

David
