### ISSUE TITLE
Could you change the remarkSource to https://remarkjs.com/

### ISSUE THREAD

**Issue by a3linux** [partageit/markdown-to-slides#10]
I found the origin one redirect to remarkjs.com one, so it is better to change the var remarkSource in compile.js to https://remarkjs.com/ one. 

Thanks.

**Comment by partageit** [comment]
Hello a3linux,
This problem is fixed, thanks to @ktrysmt.
It is available upgrading markdown-to-slides to 1.0.4.
David
