### ISSUE TITLE
improve syntax checking for document mode

### ISSUE THREAD

**Issue by leejordan** [partageit/markdown-to-slides#2]
I had problems getting document mode to convert my .md file into a slideshow and it turns out that I was using the following syntax for my headers:

`##chapter 1`

Which meant the document mode converter didn't pick these up as headings properly.

Once I converted to include a space it worked fine:

`## chapter 1`

I just thought it would be nice if the syntax checking could be a bit more flexible in this regard.

Thanks for creating a useful tool.

**Comment by leejordan** [comment]
I also feel like it should treat headings below 3 as new slides. I might be alone here but I have a markdown document where I have reached heading 4 nesting

`#### Heading 4`

and I assumed it would have created new slides out of these.

**Comment by partageit** [comment]
Hello,
Sorry for my late answer.
1. About the space between #s and the text: it seems it is not correct to remove it...
   Every documents i found deal with the space.
   Moreover, markdown-to-slides uses the marked library, which translate headings.
   So, if you really want this to be fixed, you should open a ticket here:
   https://github.com/chjj/marked
2. About the level of heading to use for a new slide, it is a good idea :)
   I will enhance markdown-to-slides to take a new parameter.

David

**Comment by partageit** [comment]
The level can be configured with the --level parameter.
For example:
markdown-to-slides -o file.html -d --level 4 file.md
Thanks for your idea :)
David

**Comment by leejordan** [comment]
Thanks for adding the level parameter it is going to be very useful.

I see your point on the syntax conversion. It just happens to be the case that other markdown tools are happy with no space between the ## and text and render it properly so it felt like this tool should have that same flexibility. I will open an issue on the library you mentioned.

**Comment by partageit** [comment]
You're right, it depends on the renderer...

For example, when a space is missing in the heading title, the same README.md is displayed as ##title on npmjs.com, and is correctly translated on GitHub...

**Comment by leejordan** [comment]
Did you update the npm package? I can't get the --level flag working after npm update

**Comment by partageit** [comment]
Yes, did you update with the `-g` parameter?

`npm update markdown-to-slides -g`

**Comment by leejordan** [comment]
Woops my bad, I'll leave these comments here in case they help anybody else :)

Thanks again!

**Comment by partageit** [comment]
:)
