### ISSUE TITLE
Is it possible to insert images?

### ISSUE THREAD

**Issue by james20141606** [partageit/markdown-to-slides#21]
Does this tool support the image insertion? I found that if I write `![](fig.png)` in the md file, there won't be any images in HTML page.

**Comment by combinatorist** [comment]
I was able to get images. Are you sure your image existed locally? Did it still exist wherever you presented etc (on a server)?

Perhaps, try a url based image first to see if the image location (locally) is the issue. For example, put this in your presentation:

```
![black and white rorschach inkblot #6 (looks vaguely like a plane)](http://norman-ai.mit.edu/img/inkblots/Rorschach_blot_06.jpg)
```

---

![black and white rorschach inkblot #6 (looks vaguely like a plane)](http://norman-ai.mit.edu/img/inkblots/Rorschach_blot_06.jpg)

**Comment by james20141606** [comment]
Thank you for your help! I found I made a mistake in my codes and it works now.
