### ISSUE TITLE
Deprecated write

### ISSUE THREAD

**Issue by danielgomezrico** [partageit/markdown-to-slides#3]
.write(string, encoding, offset, length) is deprecated. Use write(string[, offset[, length]][, encoding]) instead.

**Comment by partageit** [comment]
Where? What? Who? Why?
...

**Comment by partageit** [comment]
Ok, found...
For further open issue (here or not), please add some details, such as the nodeJS version.

**Comment by partageit** [comment]
The message is removed, replacing the old mu2 library with the more recent mustache.

**Comment by danielgomezrico** [comment]
Excuse me, :+1:

**Comment by partageit** [comment]
No problem ;)
