### ISSUE TITLE
Watch mode doesn't use specified title

### ISSUE THREAD

**Issue by davidmc24** [partageit/markdown-to-slides#4]
If I pass a title on the command-line, it works for single runs, but appears to be ignored in watch mode.

**Comment by davidmc24** [comment]
Thanks for the great tool!

**Comment by partageit** [comment]
Sorry for the delay :-s
I can't reproduce the problem, it works with this command line:

```
markdown-to-slides file.md -o file.html -w -t "My customized title"
```

`file.html` contains this HTML:

``` html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>My customized title</title>
```

Do you remember the command line you used?

The result is the same with the watch mode enabled.
